#!/bin/bash
# Setup script for career portal credentials

echo "=== Career Portal Setup ==="
echo ""
echo "1. Create GitHub Personal Access Token:"
echo "   - Go to: https://github.com/settings/tokens"
echo "   - Select: Classic token, repo scope"
echo "   - Copy the token and save it"
echo ""
echo "2. Create Cloudflare API Token:"
echo "   - Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "   - Create: Zone"
echo "   - Permissions: Zone -> Read, DNS -> Edit"
echo "   - Scope: zone.* for chai-homelab.com"
echo "   - Copy the token and save it"
echo ""
echo "3. Get Cloudflare Zone ID:"
echo "   - Go to: https://dash.cloudflare.com"
echo "   - Select: chai-homelab.com"
echo "   - Copy the Zone ID from the right sidebar"
echo ""
echo "4. Create Azure Blob Storage (if not already done):"
echo "   - Go to: https://portal.azure.com"
echo "   - Create: Storage Account > chaihomelab"
echo "   - Enable: Static website hosting (container: \$web)"
echo "   - Copy: Connection string or Account Key"
echo ""
echo "Then run:"
echo "  export GITHUB_PAT='your_token'"
echo "  export CLOUDFLARE_API_TOKEN='your_token'"
echo "  export CLOUDFLARE_ZONE_ID='your_zone_id'"
echo "  export AZURE_STORAGE_KEY='your_key'"
